{% set version = "8.0.0" %}
{% set sha256 = "95305a886f2c42e9603c034ea684e5c031d9d4222c66ed6d85eb3ae15d631e4b" %}

package:
  name: ipyparallel
  version: {{ version }}

source:
  fn: ipyparallel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipyparallel/ipyparallel-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - ipcluster = ipyparallel.cluster.app:main
    - ipcontroller = ipyparallel.controller.app:main
    - ipengine = ipyparallel.engine.app:main
  script: {{ PYTHON }} -m pip install -vv --no-deps .


requirements:
  build:
    - python >=3.6
    - pip
    - jupyterlab ==3.*

  run:
    - python >=3.6
    - decorator
    - tornado >=5.1
    - python-dateutil >=2.1
    - pyzmq >=18
    - ipython >=6
    - jupyter_client
    - ipykernel >=4.4
    - traitlets >=4.3
    - psutil
    - tqdm
    - entrypoints

test:
  requires:
    - notebook >=5.3
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize
  commands:
    - ipcluster -h
    - ipengine -h
    - ipcontroller -h

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_file: COPYING.md
  license_family: BSD
  summary: Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
